# Generated by Django 4.2 on 2023-04-08 05:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_feature_details_feature_age_feature_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
